### ISSUE TITLE
Add memory profiler ?

### ISSUE THREAD

**Issue by Nodd** [Nodd/spyder_line_profiler#18]
It is based on line_profiler, works with the same decorator ```@profile``` and has the same kind of output : https://github.com/fabianp/memory_profiler

**Comment by cmeeren** [comment]
I would VERY much like to see this. Please? Pretty please? :)

**Comment by Nodd** [comment]
Well, PR welcomed ! :)

I never actually used a memory profiler, but I might start if it is implemented in spyder...

**Comment by cmeeren** [comment]
I'm in the same boat, never used, because it wasn't implemented in Spyder, but I'd like to. :)

As for a PR, I have no experience coding user interface stuff and really didn't understand most of the spyder_line_profiler code. Is there anything in particular I can help with?
