### ISSUE TITLE
(Solution inside) Fails on Windows because kernprof.exe is run with python

### ISSUE THREAD

**Issue by cmeeren** [Nodd/spyder_line_profiler#21]
If run in Windows, fails with the following output:

      File "C:/Anaconda/Scripts/kernprof.exe", line 1
    SyntaxError: Non-ASCII character '\x90' in file C:/Anaconda/Scripts/kernprof.exe on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

This is because `kernprof.exe` is run using python: Line 264 of `lineprofilergui.py` is

```python
executable = '{0} {1}'.format(sys.executable, script_path)
```

which means `executable` is set to (in my case) `C:\Anaconda\pythonw.exe C:\Anaconda\Scripts\kernprof.exe`, whereas the correct would be only `C:\Anaconda\Scripts\kernprof.exe`.

Solution: Replace this line with

```python
executable = script_path
```

Tested and works perfectly.

**Comment by Nodd** [comment]
Thanks for the report and the solution !

I didn't test it but I'll trust you as it seems logical (kernprof used to be a python file but is now a program on its own).
