### ISSUE TITLE
Can we try turning this into pypi package and make it an installable through pip?

### ISSUE THREAD

**Issue by goanpeca** [Nodd/spyder_line_profiler#25]
Hi @Nodd, pretty cool plugin :)

What do you say if we turn this into a python package and start tryouts for a plugin manager in Spyder?

Have you ever use pypi packaging?

Cheers

**Comment by Nodd** [comment]
I'm all for it ! But I think the first step is to modify spyder itself first, so taht it can load plugins il a given namespace.

I never used pypi packaging but I've read about it. Apparentely all that it takes is a well-formed setup.py.

**Comment by goanpeca** [comment]
Hi :) good, indeed that is the plan, but I think we could work in tandem on this, I can look into spyder and you can look into uploading this as a namespacepackage in PyPI and in the process maybe documenting how you did it? (for the documentation).

I have never done it, but I have read about it as well, and yes, a well organized folder structure plus all the readmes, licenses etc.. and a `setup.py` should be enough.

In theory what Spyder should do at startup is import the plugins namespace and the __init__ should look for any module in the namespace as well, or if we wanted to have an additional "security" check, we can have a list of approved plugins inside spyder as well, to have some "supervision" of plugins. Plus we need to define a convention for the naming... `spyder-package-name` -> spyder_package_name, is the easiest one... so I guess we could use that.

**Comment by goanpeca** [comment]
And 7 months later... almost there :smile:

**Comment by Nodd** [comment]
Patience, my young padawan !

**Comment by Nodd** [comment]
It's done for spyder 3.0 (excepts that it crashes right now, but it's a detail...)
